# _config.yml
title: "Hilalum's blog"
email: "dcyap0@icloud.com"
description: ""
baseurl: ""
url: "https://hilalum.github.io"
destination: ./_site
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    path: "docs"