# _config.yml
author: "Hilalum"
title: "Hilalum's blog"
email: "dcyap0@icloud.com"
description: ""
baseurl: ""
url: "https://hilalum.github.io"
destination: ./_site
encoding: UTF-8
timezone: Asia/Shanghai
future: true # 允许发布日期在“现在”之后的文章（避免构建时被当作未来文章跳过）
google_analytics: G-QBK899EFL5
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
comments:
  provider: utterances
  repo: Hilalum/hilalum.github.io
  issue_term: pathname
  label: comment
  theme: github-light
