# _config.yml
author: "Hilalum"
title: "Hilalum's blog"
email: "dcyap0@icloud.com"
description: ""
baseurl: ""
url: "https://hilalum.github.io"
destination: ./_site
encoding: UTF-8
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    path: "docs"