# _config.yml
title: "Hilalum's blog"
email: "dcyap0@icloud.com"
description: ""
baseurl: "" 
url: "https://hilalum.github.io"
theme: "minima"  # 使用 Jekyll 的默认主题
destination: ./docs
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    directory: docs